; -------------------------------------------------------------------------
; CrazyBus sound IDs
; -------------------------------------------------------------------------

CBID_STOP		EQU	0
CBID_TITLE		EQU	1
CBID_MENU		EQU	2
CBID_BUS		EQU	3
CBID_COUNT		EQU	4
CBID_DONE		EQU	5

SAMPLE_PSG		EQU	$0000
SAMPLE_NOISE		EQU	$0100
SAMPLE_FREE		EQU	$0400

; -------------------------------------------------------------------------
