; -------------------------------------------------------------------------
; Hong Kong 97 shared data
; -------------------------------------------------------------------------

spritesExt	rs.b	$280					; Sprite buffer
hudScore	rs.l	1					; Score
hudLives	rs.b	1					; Lives
hudBombs	rs.b	1					; Bombs
hudGraze	rs.w	1					; Graze
hudBossHP	rs.w	1					; Boss HP
hudFlags	rs.b	1					; HUD flags
gameOver	rs.b	1					; Game over flag
bossCutscene	rs.b	1					; Boss cutscene flag
palChange	rs.b	1					; Palette change flag
gameWon		rs.b	1					; Game won flag

; -------------------------------------------------------------------------
